spring:
  application:
    name: 'front'
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  webflux:
    static-path-pattern: /static/**

server:
  port: 8081

api:
  core:
    port: 8090

