spring:
  application:
    name: 'front'
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    refresh: wlefhlweuffkqweyugfqlweifhnqweifhweiufhqlweifhlifliuelfqwiefleww
  security:
    oauth2:
      client:
        payco:
          registration:
            scope: profile, name, email
            code-grant-type: code
            authorization-grant-type: authorization_code
            refresh-grant-type: refresh_token
            redirect-uri: https%3a%2f%2f8248-220-67-223-57.ngrok-free.app%2foauth2%2fpayco%2fcallback
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
            user-name-attribute: id

  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  webflux:
    static-path-pattern: /static/**

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
api:
  gateway:
    port: 8090
    host: localhost

payment:
  auth-token: 'dGVzdF9za19BUTkyeW14TjM0OW5RRHBwMTJET1ZhalJLWHZkOg=='

logging:
  level:
    root: debug
nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    payco-client-id: 90da343505904a09a7545561578c021a
    payco-secret-key: 2c14c175657f4b078b93cf5f53fa45a3