spring:
  application:
    name: 'front'
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    refresh: wlefhlweuffkqweyugfqlweifhnqweifhweiufhqlweifhlifliuelfqwiefleww


  web:
    resources:
      static-locations: classpath:/static
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  webflux:
    static-path-pattern: /static/**

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

payment:
  auth-token: 'dGVzdF9za19BUTkyeW14TjM0OW5RRHBwMTJET1ZhalJLWHZkOg=='

logncrash:
  config:
    file-path: logs
    file-name: front-log
  app-key: Xyx7DoyszcG66ULx
  url: https://api-logncrash.cloud.toast.com
  version: 1.0.0
  host: aa-front
  platform: aa-front
  log:
    version: v2
    source: aa
    type: aa
